### PR TITLE
bump to 0.1.2

### PR DESCRIPTION
**Pull request by mrocklin**
@koverholt anything I'm missing here?

### CODE REVIEW

**Comment by koverholt** [comment]
This LGTM, thanks! Merging.

**Comment by koverholt** [comment]
Something odd happened here, the package was built and uploaded to anaconda.org/conda-forge/hdfs3 in this PR rather than when I merged to master just now.

Ping @conda-forge/core. See the build logs for CircleCI: https://circleci.com/gh/conda-forge/hdfs3-feedstock/2

**Comment by jakirkham** [comment]
Well, that's expected behavior actually. :smile:

The thing is all branches on the original repo autodeploy. That's why one must fork and push changes to their fork. Then one PRs back from their fork to the original repo.

**Comment by koverholt** [comment]
Oh right! Thank you for the clarification @jakirkham, always appreciated.

**Pull request merged**
